{
 "title": "Connection Maps",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "User Location and Wi-Fi Tonnage",
   "type": "grafana-worldmap-panel",
   "description": "Displays Tonnage per reported location",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "target": "db.openschemaWifiSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$unwind\": \"$metrics.location\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$sort\" : { \"ts\" : 1} },\n{ \"$project\" : {\"uuid\" : \"$identifier.uuid\", \"latitude\" : \"$metrics.location.latitude\",  \"longitude\" : \"$metrics.location.longitude\", \"ts\" : \"$timestamp.timestamp\", \"tonnage\" : { \"$divide\" : [ { \"$sum\" :  [\"$metrics.rxBytes\", \"$metrics.txBytes\" ] }, 1000000] } } }\n] )",
     "type": "table"
    }
   ]
  },
  {
   "title": "User Location and Cellular Tonnage",
   "type": "grafana-worldmap-panel",
   "description": "Displays Tonnage per reported location",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "target": "db.openschemaCellularSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$unwind\": \"$metrics.location\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$sort\" : { \"ts\" : 1} },\n{ \"$project\" : {\"uuid\" : \"$identifier.uuid\", \"latitude\" : \"$metrics.location.latitude\",  \"longitude\" : \"$metrics.location.longitude\", \"ts\" : \"$timestamp.timestamp\", \"tonnage\" : { \"$divide\" : [ { \"$sum\" :  [\"$metrics.rxBytes\", \"$metrics.txBytes\" ] }, 1000000] } } }\n] )",
     "type": "table"
    }
   ]
  },
  {
   "title": "User Location and Wi-Fi Session Duration",
   "type": "grafana-worldmap-panel",
   "description": "Displays Session Duration per reported location",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "valueName": "current",
   "targets": [
    {
     "target": "db.openschemaWifiSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$unwind\": \"$metrics.location\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$sort\" : { \"ts\" : 1} },\n{ \"$project\" : {\"uuid\" : \"$identifier.uuid\", \"latitude\" : \"$metrics.location.latitude\",  \"longitude\" : \"$metrics.location.longitude\", \"ts\" : \"$timestamp.timestamp\", \"tonnage\" : { \"$divide\" : [  \"$metrics.sessionDurationMillis\", 60000] } } }\n] )",
     "type": "table"
    }
   ]
  },
  {
   "title": "User Location and Cellular Session Duration",
   "type": "grafana-worldmap-panel",
   "description": "Displays Session Duration per reported location",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "valueName": "current",
   "targets": [
    {
     "target": "db.openschemaCellularSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$unwind\": \"$metrics.location\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$sort\" : { \"ts\" : 1} },\n{ \"$project\" : {\"uuid\" : \"$identifier.uuid\", \"latitude\" : \"$metrics.location.latitude\",  \"longitude\" : \"$metrics.location.longitude\", \"ts\" : \"$timestamp.timestamp\", \"tonnage\" : { \"$divide\" : [  \"$metrics.sessionDurationMillis\", 60000] } } }\n] )",
     "type": "table"
    }
   ]
  }
 ]
}