{
 "title": "Device Information",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Device List",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "db.openschemaDeviceInfo.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$sort\" : { \"ts\" : 1} },\n{ \"$project\" : {\"UUID\" : \"$identifier.uuid\", \"Android ID\": \"$metrics.androidId\",  \"OS Version\" : \"$metrics.osVersion\", \"Device Model\" : \"$metrics.model\",  \"Device Manufacturer\" : \"$metrics.manufacturer\", \"Device Brand\" : \"$metrics.brand\" } }\n] )",
     "type": "table"
    }
   ]
  },
  {
   "title": "Devices Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 6 },
   "valueName": "total",
   "targets": [
    {
     "target": "db.openschemaDeviceInfo.aggregate([\n{ \"$lookup\": { \"from\": \"openschemaWifiSession\", \"localField\": \"identifier.uuid\", \"foreignField\": \"identifier.uuid\", \"as\": \"Wifi_Info\" } },\n{ \"$addFields\": { \"Wifi_Info\": { \"$arrayElemAt\": [\"$Wifi_Info\", -1] } } },\n{ \"$project\": { \"metrics\": \"$metrics\", \"identifier\": \"$identifier\", \"timestamp\": \"$timestamp\", \"location\": \"$Wifi_Info.metrics.location\" } },\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$unwind\": \"$location\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$project\": { \"Device\": { \"$concat\": [ \"Device Model: \", \"$metrics.model\", \" - OS Version\"] }, \"latitude\": \"$location.latitude\", \"longitude\": \"$location.longitude\", \"osVersion\" : \"$metrics.osVersion\" } }\n] )",
     "type": "table"
    }
   ]
  },
  {
   "title": "Device Count",
   "type": "stat",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "db.openschemaDeviceInfo.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$group\" : {  \"_id\" :  \"$identifier.uuid\", \"myCount\" : { \"$sum\" : 1 }, \"ts\" : { \"$last\"  : \"$timestamp.timestamp\"} } },\n{ \"$group\" : {  \"_id\" :  \"$_id\", \"myCount\" : { \"$sum\" : 1 }, \"ts\" : { \"$last\"  : \"$ts\"} } },\n{ \"$project\" : { \"name\" : \"Unique UUID's\", \"value\" :  \"$myCount\" , \"ts\" : \"$ts\" } }\n] )",
     "type": "timeserie"
    }
   ]
  }
 ]
}