{
 "title": "Mark the Spot",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Last Reports",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "db.openschemaConnectionReport.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$unwind\": \"$metrics.location\"},\n{ \"$unwind\": \"$metrics.transportData\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$sort\" : { \"timestamp.timestamp\" : -1} },\n{ \"$project\" : { \"Timestamp\" :  { \"$dateToString\": { \"date\": \"$timestamp.timestamp\", \"format\": \"%Y-%m-%d:%H:%M:%S\"} } , \"uuid\" : \"$identifier.uuid\", \"Transport Type\" :   \"$metrics.transportType\", \"SSID\": \"$metrics.transportData.ssid\",\" BSSID\": \"$metrics.transportData.bssid\", \"Report Description\" : \"$metrics.reportDescription\", \"Status\": \"Open\"} }\n] )",
     "type": "table"
    }
   ]
  },
  {
   "title": "Total Mark the Spot Reports",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "db.openschemaConnectionReport.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$unwind\": \"$metrics.location\"},\n{ \"$unwind\": \"$metrics.transportData\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$sort\" : { \"ts\" : 1} },\n{ \"$group\": { \"_id\":  null,  \"myCount\": { \"$sum\": 1 },  \"timestamp\": { \"$last\" : \"$timestamp.timestamp\" } } },\n{ \"$project\" : { \"name\" : \"Total Mark The Spot Reports\", \"value\" :   \"$myCount\", \"ts\" : \"$timestamp\" } }\n] )",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Mark the Spot Reports",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 4, "y": 6 },
   "valueName": "total",
   "targets": [
    {
     "target": "db.openschemaConnectionReport.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$unwind\": \"$metrics.location\"},\n{ \"$unwind\": \"$metrics.transportData\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$sort\" : { \"ts\" : 1} },\n{ \"$project\" : {\"report\" : \"$metrics.reportDescription\", \"latitude\" : \"$metrics.location.latitude\",  \"longitude\" : \"$metrics.location.longitude\", \"ts\" : \"$timestamp.timestamp\",  \"count\" :  \"1\" } }\n] )",
     "type": "table"
    }
   ]
  }
 ]
}