{
 "title": "Tonnage and Time",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total Cellular vs Wi-fi GB",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "db.openschemaWifiSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$project\" : { \"time\" : \"$timestamp.timestamp\",  \"totalBytes\" : { \"$sum\" :  [\"$metrics.rxBytes\", \"$metrics.txBytes\" ] } } },\n{ \"$group\" : {  \"_id\" :  \"$time\", \"totalBytes\" :  { \"$sum\" : \"$totalBytes\" } } },\n{ \"$sort\" : {\"_id\" : 1}  },\n{ \"$project\" : { \"name\" : \"Total GB on Wi-Fi\", \"value\" :  { \"$divide\" : [ \"$totalBytes\", 1000000000] } , \"ts\" : \"$_id\" } }\n] )",
     "type": "timeserie"
    },
    {
     "target": "db.openschemaCellularSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$project\" : { \"time\" : \"$timestamp.timestamp\",  \"totalBytes\" : { \"$sum\" :  [\"$metrics.rxBytes\", \"$metrics.txBytes\" ] } } },\n{ \"$group\" : {  \"_id\" :  \"$time\", \"totalBytes\" :  { \"$sum\" : \"$totalBytes\" } } },\n{ \"$sort\" : {\"_id\" : 1}  },\n{ \"$project\" : { \"name\" : \"Total GB on Cellular\", \"value\" :  { \"$divide\" : [ \"$totalBytes\", 1000000000] } , \"ts\" : \"$_id\" } }\n] )",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Unique UUID's",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.openschemaWifiSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$group\" : {  \"_id\" :  \"$identifier.uuid\", \"myCount\" : { \"$sum\" : 1 }, \"ts\" : { \"$last\"  : \"$timestamp.timestamp\"} } },\n{ \"$group\" : {  \"_id\" :  \"$_id\", \"myCount\" : { \"$sum\" : 1 }, \"ts\" : { \"$last\"  : \"$ts\"} } },\n{ \"$project\" : { \"name\" : \"Unique UUID's\", \"value\" :  \"$myCount\" , \"ts\" : \"$ts\" } }\n] )",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Session Duration vs Data Usage - Wi-Fi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Hours" }
   ],
   "targets": [
    {
     "target": "db.openschemaWifiSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$project\" : { \"year\" : { \"$year\" : \"$timestamp.timestamp\" }, \"month\": { \"$month\" : \"$timestamp.timestamp\" }, \"day\" : { \"$dayOfMonth\" : \"$timestamp.timestamp\" }, \"hour\" : { \"$hour\" : \"$timestamp.timestamp\" },  \"sessionDurationMillis\" :  \"$metrics.sessionDurationMillis\",  \"ts\": \"$timestamp.timestamp\"} },\n{ \"$group\" : {  \"_id\" :  { \"year\":\"$year\",\"month\":\"$month\",\"day\":\"$day\",\"hour\":\"$hour\"}, \"totalMilliseconds\" : { \"$sum\" : \"$sessionDurationMillis\" }, \"ts\": { \"$last\" : \"$ts\" } } },\n{ \"$sort\" : {\"ts\" : 1}},  \n{ \"$project\" : { \"name\" : \"Wi-Fi Connection Duration Hours\", \"value\" :  { \"$divide\" : [ \"$totalMilliseconds\", 3600000] } , \"ts\" : \"$ts\" } }\n] )",
     "type": "timeserie"
    },
    {
     "target": "db.openschemaWifiSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$project\" : { \"year\" : { \"$year\" : \"$timestamp.timestamp\" }, \"month\": { \"$month\" : \"$timestamp.timestamp\" }, \"day\" : { \"$dayOfMonth\" : \"$timestamp.timestamp\" }, \"hour\" : { \"$hour\" : \"$timestamp.timestamp\" },  \"totalBytes\" : { \"$sum\" :  [\"$metrics.rxBytes\", \"$metrics.txBytes\" ] },  \"ts\": \"$timestamp.timestamp\"} },\n{ \"$group\" : {  \"_id\" :  { \"year\":\"$year\",\"month\":\"$month\",\"day\":\"$day\",\"hour\":\"$hour\"}, \"totalBytes\" :  { \"$sum\" : \"$totalBytes\" }, \"ts\": { \"$last\" : \"$ts\" } } },\n{ \"$sort\" : {\"ts\" : 1}}, \n{ \"$project\" : { \"name\" : \"Total GB on Wi-Fi\", \"value\" :  { \"$divide\" : [ \"$totalBytes\", 1000000000] } , \"ts\" : \"$ts\" } }\n] )",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Session Duration vs Data Usage - Cellular",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Hours" }
   ],
   "targets": [
    {
     "target": "db.openschemaCellularSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$project\" : { \"year\" : { \"$year\" : \"$timestamp.timestamp\" }, \"month\": { \"$month\" : \"$timestamp.timestamp\" }, \"day\" : { \"$dayOfMonth\" : \"$timestamp.timestamp\" }, \"hour\" : { \"$hour\" : \"$timestamp.timestamp\" },  \"sessionDurationMillis\" :  \"$metrics.sessionDurationMillis\",  \"ts\": \"$timestamp.timestamp\"} },\n{ \"$group\" : {  \"_id\" :  { \"year\":\"$year\",\"month\":\"$month\",\"day\":\"$day\",\"hour\":\"$hour\"}, \"totalMilliseconds\" : { \"$sum\" : \"$sessionDurationMillis\" }, \"ts\": { \"$last\" : \"$ts\" } } },\n{ \"$sort\" : {\"ts\" : 1} },\n{ \"$project\" : { \"name\" : \"Cellular Connection Duration Hours\", \"value\" :  { \"$divide\" : [ \"$totalMilliseconds\", 3600000] } , \"ts\" : \"$ts\" } }\n] )",
     "type": "timeserie"
    },
    {
     "target": "db.openschemaCellularSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$project\" : { \"year\" : { \"$year\" : \"$timestamp.timestamp\" }, \"month\": { \"$month\" : \"$timestamp.timestamp\" }, \"day\" : { \"$dayOfMonth\" : \"$timestamp.timestamp\" }, \"hour\" : { \"$hour\" : \"$timestamp.timestamp\" },  \"totalBytes\" : { \"$sum\" :  [\"$metrics.rxBytes\", \"$metrics.txBytes\" ] },  \"ts\": \"$timestamp.timestamp\"} },\n{ \"$group\" : {  \"_id\" :  { \"year\":\"$year\",\"month\":\"$month\",\"day\":\"$day\",\"hour\":\"$hour\"}, \"totalBytes\" :  { \"$sum\" : \"$totalBytes\" }, \"ts\": { \"$last\" : \"$ts\" } } },\n{ \"$sort\" : {\"ts\" : 1} },\n{ \"$project\" : { \"name\" : \"Total GB on Cellular\", \"value\" :  { \"$divide\" : [ \"$totalBytes\", 1000000000] } , \"ts\" : \"$ts\" } }\n] )",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Wi-Fi Data Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "db.openschemaWifiSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$project\" : { \"name\" : \"Wi-Fi Rx GB\", \"value\" : { \"$divide\": [ \"$metrics.rxBytes\", 1000000000  ] } , \"ts\" : \"$timestamp.timestamp\" } }\n] )",
     "type": "timeserie"
    },
    {
     "target": "db.openschemaWifiSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$match\" : {  \"identifier.clientType\" : \"android\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$project\" : { \"name\" : \"Wi-Fi Tx GB\", \"value\" : { \"$divide\": [ \"$metrics.txBytes\", 1000000000  ] } , \"ts\" : \"$timestamp.timestamp\" } }\n] )",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Cellular Data by Network Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "db.openschemaCellularSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$match\" : {  \"metrics.networkType\" : \"4G\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$project\" : { \"time\" : \"$timestamp.timestamp\",  \"totalBytes\" : { \"$sum\" :  [\"$metrics.rxBytes\", \"$metrics.txBytes\" ] } } },\n{ \"$project\" : { \"name\" : \"4G\", \"value\" :  { \"$divide\" : [ \"$totalBytes\", 1000000000] } , \"ts\" : \"$time\" } }\n] )",
     "type": "timeserie"
    },
    {
     "target": "db.openschemaCellularSession.aggregate([\n{ \"$unwind\": \"$metrics\"},\n{ \"$unwind\": \"$identifier\"},\n{ \"$unwind\": \"$timestamp\"},\n{ \"$match\" : {  \"metrics.networkType\" : \"3G\", \"timestamp.timestamp\" : { \"$gte\" : \"$from\", \"$lte\" : \"$to\" } } },\n{ \"$project\" : { \"time\" : \"$timestamp.timestamp\",  \"totalBytes\" : { \"$sum\" :  [\"$metrics.rxBytes\", \"$metrics.txBytes\" ] } } },\n{ \"$project\" : { \"name\" : \"3G\", \"value\" :  { \"$divide\" : [ \"$totalBytes\", 1000000000] } , \"ts\" : \"$time\" } }\n] )",
     "type": "timeserie"
    }
   ]
  }
 ]
}