/*
 * Copyright (c) 2020, The Magma Authors
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.openschema.mma.data.entity;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Entity class used by Room to store network usage locally. Entries will be split on an hourly-basis.
 */
//TODO: javadocs
@Entity(tableName = "network_usage")
public class NetworkUsageEntity {
    /**
     * Autogenerated ID for Room database
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    public int mId = 0;

    @ColumnInfo(name = "transport_type")
    public int mTransportType;

    //Stored in milliseconds
    @ColumnInfo(name = "duration")
    public long mDuration;

    //Stored in bytes
    @ColumnInfo(name = "usage")
    public long mUsage;

    @ColumnInfo(name = "timestamp")
    public long mTimeStamp;

    public NetworkUsageEntity(int transportType, long duration, long usage, long timeStamp) {
        mTransportType = transportType;
        mDuration = duration;
        mUsage = usage;
        mTimeStamp = timeStamp;
    }
}