//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: metricsd.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate Magma_Orc8r_MetricsControllerClient, then call methods of this protocol to make API calls.
public protocol Magma_Orc8r_MetricsControllerClientProtocol: GRPCClient {
  func collect(
    _ request: Magma_Orc8r_MetricsContainer,
    callOptions: CallOptions?
  ) -> UnaryCall<Magma_Orc8r_MetricsContainer, Magma_Orc8r_Void>

  func push(
    _ request: Magma_Orc8r_PushedMetricsContainer,
    callOptions: CallOptions?
  ) -> UnaryCall<Magma_Orc8r_PushedMetricsContainer, Magma_Orc8r_Void>

}

extension Magma_Orc8r_MetricsControllerClientProtocol {

  /// Report a collection of metrics from a service
  ///
  /// - Parameters:
  ///   - request: Request to send to Collect.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func collect(
    _ request: Magma_Orc8r_MetricsContainer,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Magma_Orc8r_MetricsContainer, Magma_Orc8r_Void> {
    return self.makeUnaryCall(
      path: "/magma.orc8r.MetricsController/Collect",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
    
  }

  /// Push a collection of metrics to metricsd
  ///
  /// - Parameters:
  ///   - request: Request to send to Push.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func push(
    _ request: Magma_Orc8r_PushedMetricsContainer,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Magma_Orc8r_PushedMetricsContainer, Magma_Orc8r_Void> {
    return self.makeUnaryCall(
      path: "/magma.orc8r.MetricsController/Push",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

public final class Magma_Orc8r_MetricsControllerClient: Magma_Orc8r_MetricsControllerClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the magma.orc8r.MetricsController service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

