/*
 * Copyright (c) 2020, The Magma Authors
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.openschema.mma.data.entity;

import java.util.List;

import androidx.core.util.Pair;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;
import io.openschema.mma.data.pojo.Timestamp;

/**
 * Entity class used by Room to store a Metrics object
 */
//TODO: Consider adding logic to delete unsent metrics that are too old
@Entity(tableName = "metrics")
public class MetricsEntity {
    /**
     * Autogenerated ID for Room database
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    private int id = 0;

    /**
     * Name used by the metric.
     */
    @ColumnInfo(name = "metric_name")
    private String metricName;

    /**
     * List of collected metrics with the <name, value> structure.
     */
    @ColumnInfo(name = "metrics_list")
    private List<Pair<String, String>> metricsList;

    /**
     * Timestamp to attach to the metric.
     */
    @ColumnInfo(name = "timestamp")
    private Timestamp timestamp;

    @Ignore
    public MetricsEntity(String metricName, List<Pair<String, String>> metricsList, Timestamp timestamp) {
        this(0, metricName, metricsList, timestamp);
    }

    /**
     * Constructor with all fields. Required for Android Room.
     */
    public MetricsEntity(int id, String metricName, List<Pair<String, String>> metricsList, Timestamp timestamp) {
        this.id = id;
        this.metricName = metricName;
        this.metricsList = metricsList;
        this.timestamp = timestamp;
    }

    public int getId() { return id;}
    public String getMetricName() {return metricName;}
    public List<Pair<String, String>> getMetricsList() {return metricsList;}
    public Timestamp getTimestamp() { return timestamp;}
}