/*
 * Copyright (c) 2020, The Magma Authors
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.openschema.mma.data.entity;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/**
 * Entity class used by Room to store network quality locally.
 */
@Entity(tableName = "network_quality")
public class NetworkQualityEntity {
    /**
     * Autogenerated ID for Room database
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    private int id = 0;

    //Need to look for network connection ID + transport type as a composite key
    //Network connection ID can cause issues due to ID duplicating in WiFiConnectionsEntity and CellularConnectionsEntity
    @ColumnInfo(name = "network_connection_id")
    private int networkConnectionId;

    @ColumnInfo(name = "transport_type")
    private int transportType;

    @ColumnInfo(name = "quality_score")
    private double qualityScore;

    @ColumnInfo(name = "rtt")
    private double rtt;

    @ColumnInfo(name = "rssi")
    private int rssi;

    @ColumnInfo(name = "timestamp")
    private long timestamp;

    @Ignore
    public NetworkQualityEntity(int networkConnectionId, int transportType, double qualityScore, double rtt, int rssi, long timestamp) {
        this(0, networkConnectionId, transportType, qualityScore, rtt, rssi, timestamp);
    }

    /**
     * Constructor with all fields. Required for Android Room.
     */
    public NetworkQualityEntity(int id, int networkConnectionId, int transportType, double qualityScore, double rtt, int rssi, long timestamp) {
        this.id = id;
        this.networkConnectionId = networkConnectionId;
        this.transportType = transportType;
        this.qualityScore = qualityScore;
        this.rtt = rtt;
        this.rssi = rssi;
        this.timestamp = timestamp;
    }

    public int getId() { return id;}
    public int getNetworkConnectionId() { return networkConnectionId;}
    public int getTransportType() {return transportType;}
    public double getQualityScore() {return qualityScore;}
    public double getRtt() {return rtt;}
    public int getRssi() {return rssi;}
    public long getTimestamp() {return timestamp;}
}