/*
 * Copyright (c) 2020, The Magma Authors
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.openschema.mma.data;

import java.util.List;

import androidx.core.util.Pair;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Entity class used by Room to store a Metrics object
 */
//TODO: Consider adding logic to delete unsent metrics that are too old
@Entity(tableName = "metrics_entity")
public class MetricsEntity {
    /**
     * Autogenerated ID for Room database
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    public int mId = 0;

    /**
     * Name used by the metric family in Prometheus.
     */
    @ColumnInfo(name = "familyName")
    public String mFamilyName;

    /**
     * Timestamp to attach to the metric.
     */
    @ColumnInfo(name = "timestamp")
    public String mTimeStamp;

    /**
     * List of collected metrics with the <name, value> structure.
     */
    @ColumnInfo(name = "metrics")
    public List<Pair<String, String>> mMetrics;

    public MetricsEntity(String familyName, String timeStamp, List<Pair<String, String>> metrics) {
        mFamilyName = familyName;
        mTimeStamp = timeStamp;
        mMetrics = metrics;
    }
}